#! /bin/sh

usage() {
	echo ""
}

BASEDIR="/sys/class/backlight/intel_backlight"

_show_max_brightness() {
	echo "max_brightness: $(cat $BASEDIR/max_brightness)"
}


_set_brightness() {
	echo $1 > $BASEDIR/brightness
}

main() {
	if [ $# -eq 0 ] ; then
		_show_max_brightness
	else
		_set_brightness $1
	fi
}

main "$@"
